### ISSUE TITLE
npm install @workpathco/client --save does not work

### ISSUE THREAD

**Issue by ccahcares** [workpathco/client#9]
* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

I want to create a zapier integration for workpath and I'm not 100% sure but I don't think I can use yarn in my build script.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by rstims** [comment]
@ccahcares Hi! That little piece of code is annoying. I'll take it out and push up a release. Let us know if you run into anything else or need help with anything for your integration. Thanks!

**Comment by rstims** [comment]
https://www.npmjs.com/package/@workpathco/client/v/1.0.41
